### ISSUE TITLE
Basic formatting bar & help

### ISSUE THREAD

**Issue by tomasc** [tomasc/simple_form_markdown_editor#1]
I very much like the editor GitHub has for editing its Wiki Pages!
See screenshot.

![screen shot 2015-02-28 at 10 29 27](https://cloud.githubusercontent.com/assets/3788/6425657/dd5c5b9a-bf34-11e4-9a1c-0a3a76c1addc.png)

**Comment by asgerb** [comment]
Notes:
https://github.com/samknight/gollum_editor/blob/master/lib/assets/javascripts/gollum_editor/gollum.editor.js
http://jfrolich.github.io/simple-markdown-editor/
